### ISSUE TITLE
GeoInterfaceRecipes precompilation error with GeoInterface v1.5

### ISSUE THREAD

**Issue by bclyons12** [JuliaGeo/GeoInterface.jl#200]
GeoInterfaceRecipes can't precompile with the new GeoInterface v1.5. Downgrading to v1.4.1 solves this issue. Right now other upstream packages like LibGEOS require GeoInterfaceRecipes, so a whole software stack can't precompile.

```
julia> versioninfo()
Julia Version 1.11.6
Commit 9615af0f269 (2025-07-09 12:58 UTC)
Build Info:
  Official https://julialang.org/ release
Platform Info:
  OS: macOS (arm64-apple-darwin24.0.0)
  CPU: 12 × Apple M4 Pro
  WORD_SIZE: 64
  LLVM: libLLVM-16.0.6 (ORCJIT, apple-m1)
Threads: 8 default, 0 interactive, 4 GC (on 8 virtual cores)
Environment:
  JULIA_NUM_THREADS = auto

julia> import Pkg; Pkg.activate(temp=true)
  Activating new project at `/var/folders/nt/ct_lf2n94_1c21908mmbx55w0000gq/T/jl_FMl6kv`

(jl_FMl6kv) pkg> add GeoInterfaceRecipes
[ Info: Use `./GeoInterfaceRecipes` to add or develop the local directory at `~/.julia/compiled/v1.11/GeoInterfaceRecipes`.
   Resolving package versions...
    Updating `/private/var/folders/nt/ct_lf2n94_1c21908mmbx55w0000gq/T/jl_FMl6kv/Project.toml`
  [0329782f] + GeoInterfaceRecipes v1.0.2
    Updating `/private/var/folders/nt/ct_lf2n94_1c21908mmbx55w0000gq/T/jl_FMl6kv/Manifest.toml`
  [9a962f9c] + DataAPI v1.16.0
  [411431e0] + Extents v0.1.6
  [68eda718] + GeoFormatTypes v0.4.4
  [cf35fbd7] + GeoInterface v1.5.0
  [0329782f] + GeoInterfaceRecipes v1.0.2
⌅ [aea7be01] + PrecompileTools v1.2.1
  [21216c6a] + Preferences v1.4.3
  [3cdcf5f2] + RecipesBase v1.3.4
  [ade2ca70] + Dates v1.11.0
  [de0858da] + Printf v1.11.0
  [fa267f1f] + TOML v1.0.3
  [4ec0a83e] + Unicode v1.11.0
        Info Packages marked with ⌅ have new versions available but compatibility constraints restrict them from upgrading. To see why use `status --outdated -m`
Precompiling project...
  ? GeoInterfaceRecipes

julia> import GeoInterfaceRecipes
Precompiling GeoInterfaceRecipes...
Info Given GeoInterfaceRecipes was explicitly requested, output will be shown live 
WARNING: Method definition apply_recipe(Base.AbstractDict{Symbol, Any}, Union{GeoInterface.MultiPointTrait, GeoInterface.PointTrait}, Any) in module GeoInterfaceRecipesBaseExt at /Users/lyons/.julia/packages/RecipesBase/BRe07/src/RecipesBase.jl:296 overwritten in module GeoInterfaceRecipes on the same line (check for duplicate calls to `include`).
ERROR: Method overwriting is not permitted during Module precompilation. Use `__precompile__(false)` to opt-out of precompilation.
  ? GeoInterfaceRecipes
[ Info: Precompiling GeoInterfaceRecipes [0329782f-3d07-4b52-b9f6-d3137cf03c7a] 
WARNING: Method definition apply_recipe(Base.AbstractDict{Symbol, Any}, Union{GeoInterface.MultiPointTrait, GeoInterface.PointTrait}, Any) in module GeoInterfaceRecipesBaseExt at /Users/lyons/.julia/packages/RecipesBase/BRe07/src/RecipesBase.jl:296 overwritten in module GeoInterfaceRecipes on the same line (check for duplicate calls to `include`).
ERROR: Method overwriting is not permitted during Module precompilation. Use `__precompile__(false)` to opt-out of precompilation.
┌ Info: Skipping precompilation due to precompilable error. Importing GeoInterfaceRecipes [0329782f-3d07-4b52-b9f6-d3137cf03c7a].
└   exception = Error when precompiling module, potentially caused by a __precompile__(false) declaration in the module.
```

**Comment by asinghvi17** [comment]
ah damn, we have to retroactively cap everything in the registry...

**Comment by asinghvi17** [comment]
But we are also getting prs out now, fwiw
